modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="annabethscore"
version="${file.jarVersion}"
displayName="Annabeth's Core"
authors="gayannabeth"
description='''
Shared code for all my mods
'''
[[dependencies.annabethscorse]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
